name: Docker Build and Push

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Additional tag for the Docker image'
        required: false
        type: string
        default: ''

env:
  DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            betterweb/docker-socket-over-ssh-nfs-client:latest
            betterweb/docker-socket-over-ssh-nfs-client:${{ github.sha }}
            ${{ github.event.inputs.tag != '' && format('betterweb/docker-socket-over-ssh-nfs-client:{0}', github.event.inputs.tag) || '' }} 